### ISSUE TITLE
[Symfony 3.4] Templating service issue

### ISSUE THREAD

**Issue by Adraesh** [whatwedo/TableBundle#11]
Hello,

Trying to run the bundle in Symfony 3.4:

> The service "whatwedo_table.table" has a dependency on a non-existent service "templating".

In Symfony 3.4 the service templating has been replaced by assets.package

**Comment by tuxes3** [comment]
You need to enable the templating component in your config:

    framework:
        templating:
            engines: ['twig']

We will update our documentation.
