### ISSUE TITLE
Saved Filters can't be applied

### ISSUE THREAD

**Issue by 71m024** [whatwedo/TableBundle#12]
When pressing on "Gespeicherte Filter", nothing happens (no js-error occures).

![Bildschirmfoto 2019-04-15 um 16 47 17](https://user-images.githubusercontent.com/4126466/56142368-d71d3d80-5f9e-11e9-8c9e-424b931c5fb2.png)

**Comment by rugbymauri** [comment]
popover from the bootstrap.js is needed

popover must be initialized with
```
$('[data-toggle="popover"]').popover({
        // importatant!!
        sanitize: false,
    });
```
