### ISSUE TITLE
default-value of sortable-option

### ISSUE THREAD

**Issue by 71m024** [whatwedo/TableBundle#17]
Shouldn't the default-value of the sortable-option be `false`?  
Because, if the column refers to an other table, the sort-request ends in a failing query like this:  

``` sql
SELECT DISTINCT id_1
FROM (
	SELECT DISTINCT id_1, s0_.competence_id
	FROM (
		SELECT
		s0_.id AS id_1,
		s0_.is_active AS is_active_2,
		FROM student s0_ 
	) dctrn_result_inner
	ORDER BY s0_.competence_id ASC
) dctrn_result LIMIT 25;
```

**Comment by tuxes3** [comment]
The sort expression has to be set manually in this case. The bundle cannot know which property to sort if it is a relation, as `id` would not make a lot of sense. 

```php
    ->addColumn('competence', null, [
        'sort_expression' => 'competence.name'
    ])
```

is what you are looking for.
