### ISSUE TITLE
Open view in a new tab

### ISSUE THREAD

**Issue by kn0blauch** [whatwedo/TableBundle#34]
# Is

When being in a overview with many records in a list, then I can open a single record in the current tab only.

This is not convenient.

# Should

- [ ] List items can be open in a new tab via browser functions (same like pressing the arrow "Details" on the right)

**Comment by tuxes3** [comment]
is possible with:

```php
        $table->addAction('showInNewTab', [
            ...
            'attr' => [
                'target' => '_blank',
            ],
        ]);
```
