### ISSUE TITLE
isNull expression AjaxRelationFilterType doesn't work

### ISSUE THREAD

**Issue by ArnoEgli** [whatwedo/TableBundle#41]
https://github.com/whatwedo/TableBundle/blob/e2aa472f82f2816d0b5a3962c179fd237512dafc/src/Filter/Type/AjaxRelationFilterType.php#L62

https://github.com/whatwedo/TableBundle/blob/e2aa472f82f2816d0b5a3962c179fd237512dafc/src/EventListener/FilterEventListener.php#L100-L104

If the filter is sent empty, there is a 500 error: `get_class(): Argument #1 ($object) must be of type object, string given`

**Comment by tuxes3** [comment]
weird that `->isNull` returns a string and not a `Comparision`.
