### ISSUE TITLE
Filter as Extension

### ISSUE THREAD

**Issue by n3r0-ch** [whatwedo/TableBundle#6]
Allow to use table without filter

**Comment by xarem** [comment]
@s4mpl3d 

Bitte erweitere die FilterExtension dass der QUERY_PREDEFINED_FILTER den table identifier prefixt. 

Aktuell:

`?predefined_filter=NAME`

Neu:

`tableidentifier_predefined_filter=NAME` 

Beispiel: Table::getActionQueryParameter()

Zudem die Dokumentation nachführen in `Resources/doc/table-configuration.md`

**Comment by xarem** [comment]
@s4mpl3d 

Bitte verschiebe FilterBuilder vom Namespace `whatwedo\TableBundle\Extension` in `whatwedo\TableBundle\Builder` und aktualisiere allfällige Abhängigkeiten in den Projekten (sollten aber noch keine existieren meines Wissens)
