### ISSUE TITLE
Define default filters

### ISSUE THREAD

**Issue by n3r0-ch** [whatwedo/TableBundle#9]
Add possibility to define default filters which can be edited and removed

**Comment by xarem** [comment]
@Tuxes3 es müssen mehrere vordefinierte Filter mit eindeutigen Identifiern bei einer Definition hinzugefügt werden können, welche direkt aufgerufen werden können, um eine vordefinierte Filteransicht zu ermöglichen (z.B. nur offene Rechnungen). Diese werden nicht in der Datenbank gespeichert.
